### PR TITLE
Update line 54: wallet to wallet_ss58

### PR DESCRIPTION
**Pull request by Jackalgirl**
This will hopefully solve some issues where miners are not getting requests, as per cocofreddie's fix in the Opentensor Discord, here: https://discord.com/channels/799672011265015819/1161764867166961704/1169952256536354867

### CODE REVIEW

**Review by shibshib — APPROVED** [review]

**Review by Eugene-hu — CHANGES_REQUESTED** [review]
hey @Jackalgirl , thanks for the changes. I can confirm that is a bug in the current text prompting. 

However, we have strict rules on PRs for master branch, instead can I ask you to point your PR to the staging branch? We will include in a upcoming release.

**Comment by Jackalgirl** [comment]
> hey @Jackalgirl , thanks for the changes. I can confirm that is a bug in the current text prompting.
> 
> However, we have strict rules on PRs for master branch, instead can I ask you to point your PR to the staging branch? We will include it in a upcoming release.

Thank you for pointing that out -- I'll make sure I do it correctly from here on out : )

Change made and re-review requested! (at least, I hope I did it right!)

**Review by Eugene-hu — APPROVED** [review]

**Comment by Eugene-hu** [comment]
> Thank you for pointing that out -- I'll make sure I do it correctly from here on out : )
> 
> Change made and re-review requested! (at least, I hope I did it right!)

Amazing, LGTM!

**Review by ifrit98 — APPROVED** [review]
LGTM!

**Pull request merged**
